### PR TITLE
fix(install.sh): support windows mingw platform

### PR DESCRIPTION
**Pull request by ahaoboy**
```
 uname -s
MINGW64_NT-10.0-22635

```

### CODE REVIEW

**Review by zkochan — APPROVED** [review]

**Comment by ahaoboy** [comment]
@zkochan  How to update SHASUMS256.txt file? I don't know if it's because of the difference in Win platforms, but the result of the command is not the same https://github.com/pnpm/get.pnpm.io/blob/main/CONTRIBUTING.md.

```
 sha256sum install.sh  > SHASUMS256.txt
```

This will update the hash values of all files.
```
 sh ./_update.sh 
```

**Comment by zkochan** [comment]
You cannot update it because it has to be signed. I have updated them.

**Comment by ahaoboy** [comment]
> Powershell on ubuntu fails now

Is this PR the cause? I only changed install.sh and not any ps scripts.

**Comment by ahaoboy** [comment]
> Powershell on ubuntu fails now

It seems to be a problem with the latest version of pwsh, I don't know if mac is affected as well.
https://github.com/pnpm/get.pnpm.io/pull/40

**Pull request merged**
