### PR TITLE
feat: use GitHub to download releases

### PR DESCRIPTION
**Pull request by tucksaun**
As requested in https://github.com/pnpm/get.pnpm.io/pull/28#issuecomment-1345150562

### CODE REVIEW

**Comment by zkochan** [comment]
Some of the checks are failing.

**Comment by tucksaun** [comment]
As far as I can tell, those failings are the same ones failing on `main` and for the same reasons:
- tested shells (dash and sh) are not supported by `pnpm` setup
- regarding ksh, it does not support `local` keyword

do you want a PR to remove them from the matrix?

**Comment by zkochan** [comment]
This should fix `pnpm setup` for dash,  ksh and sh: https://github.com/pnpm/components/pull/6

**Comment by zkochan** [comment]
ok, I have managed to fix the actions. Everything is passing! I'll review later.

**Review by zkochan — APPROVED** [review]

**Pull request merged**
