### PR TITLE
feat: support download under Alpine

### PR DESCRIPTION
**Pull request by bvanjoi**
Help user to download right binary under Alpine

related issue: https://github.com/pnpm/pnpm/issues/5955

### CODE REVIEW

**Comment by zkochan** [comment]
Isn't this solved by https://github.com/pnpm/get.pnpm.io/pull/28?

**Comment by bvanjoi** [comment]
> Isn't this solved by #28?

It doesn't seem to be able to distinguish between x86 and arm64

**Comment by zkochan** [comment]
This doesn't work for alpine?

https://github.com/pnpm/get.pnpm.io/blob/f833b8daaf9e92a25d298e9b4c9e18ae93d57e66/install.sh#L68-L91

**Comment by bvanjoi** [comment]
it works

image

**Pull request closed without merging**
